version: "3.1"
services:
  springboo:
    image: vibishanan/spring-boot:tag
    restart: always # This will be ignored if we deploy in docker swarm
    ports:
    - 8080:8080
    networks:
    - springbootnet
  mongoD:
    image: mongo
    volumes:
    - mongos:/data/db
    networks:
    - springbootnet
volumes:
  mongos:
    driver: local
networks:
  springbootnet:
